version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/code/partner-eb-meanstack-atlas"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/code/partner-eb-meanstack-atlas/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/code/partner-eb-meanstack-atlas/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
